from django.urls import path
from . import views

urlpatterns = [
    path('', views.IndexView.as_view(), name="index"),
    path('fil/index/', views.IndexView.as_view(), name="index"),
    path('fil/student/create_student/', views.CreateStudentView.as_view(), name='create_student'),
    path('fil/student/<str:student_code>/student_detail', views.StudentDetailView.as_view(), name='student_detail'),
    path('fil/students/', views.StudentsView.as_view(), name="students"),
    path('fil/student/<str:student_code>/edit/', views.EditStudentView.as_view(), name='edit_student'),
    path('fil/student/<str:student_code>/delete/', views.DeleteStudentView.as_view(), name='delete_student'),
    path('fil/donor/create_donor/', views.create_donor, name='create_donor'),
    path('fil/donor/<str:donor_code>/donor_detail', views.donor_detail, name='donor_detail'),
    path('fil/donors/', views.donor_view, name="donors"),
    path('fil/donor/<str:donor_code>/edit/', views.edit_donor, name='edit_donor'),
    path('fil/donor/<str:donor_code>/delete/', views.delete_donor, name='delete_donor'),
    path('fil/student/<str:student_code>/create_alert/', views.create_alert, name='create_alert'),
    path('fil/philanthropy/create_philanthropy/', views.create_philanthropy, name='create_philanthropy'),
    path('fil/philanthropy/', views.philanthropy_view, name='philanthropy'),
    path('fil/philanthropy/<str:philanthropy_code>/philanthropy_detail',
         views.philanthropy_detail, name='philanthropy_detail'),
    path('fil/philanthropy/<str:philanthropy_code>/edit/',
         views.philanthropy_edit, name='philanthropy_edit'),
    path('fil/philanthropy/<str:philanthropy_code>/delete/', views.philanthropy_delete, name='delete_philanthropy'),
    path('fil/reports/', views.GenerateReportView.as_view(), name='reports'),
    path('fil/reports/generate', views.ReportGenerateView.as_view(), name='reports_generate'),
    path('fil/reports/base_reports', views.BaseReportsView.as_view(), name='base_reports'),
    path('fil/reports/pdf/becas', views.BecasReportView.as_view(), name='becas_report'),
    path('fil/reports/pdf/extra', views.ExtraReportView.as_view(), name='extra_report'),
    path('fil/reports/pdf/CREA', views.CreaReportView.as_view(), name='crea_report'),
    path('fil/reports/pdf/CREA/<str:student_code>', views.QueryStudentCreaView.as_view(), name='query_student_crea'),
    path('fil/reports/pdf/extra/<str:student_code>', views.QueryStudentExtraView.as_view(), name='query_student_extra'),
    path('fil/reports/pdf/becas/<str:student_code>', views.QueryStudentBecasView.as_view(), name='query_student_becas'),
    #path('fil/reports/true', views.show_modal, name='show_modal'),
    path('fil/registrate/', views.registrate_user, name='registrate'),
    path('fil/salir/', views.salir, name='salir'),
    path('fil/alerts/', views.see_alerts, name='alerts'),
    path('fil/alerts/<str:alert_code>', views.alert_detail, name='alert_detail'),
    path('fil/info_management/', views.info_management, name='info_management'),
    path('fil/info_dissemination/', views.info_dissemination, name='info_dissemination'),
    path('fil/info_dissemination/send', views.send_info, name='send_info'),
    path('fil/info_dissemination/show', views.show_info, name='show_info'),
    path('fil/request_update/', views.request_update, name='request_update'),
    path('fil/info_dissemination/show', views.show_info, name='show_info')
]
