from .student_view import *
from .home_view import *
from .donor_view import *
from .report_view import *
from .philanthropy_view import *
from .alert_view import *
from .registrate_view import *
from .logout_view import *
from .alert_view import *
from .info_management import *
from .request_update_view import *
from .info_management import *
from .info_dissemination_view import *
from .import_students_view import *
