# Generated by Django 4.2.5 on 2023-10-01 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collaborator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collaborator_code', models.CharField(max_length=10)),
                ('collaborator_name', models.CharField(max_length=24)),
                ('collaborator_email', models.CharField(max_length=24)),
                ('collaborator_allow_alert', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_code', models.CharField(max_length=12, unique=True)),
                ('donor_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PhilanthropyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('philanthropy_member_code', models.CharField(max_length=10)),
                ('philanthropy_member_name', models.CharField(max_length=24)),
                ('philanthropy_member_email', models.CharField(default='default@gmail.com', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TypeAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type_code', models.CharField(max_length=12, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypeCollaborator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_collaborator_code', models.CharField(max_length=10)),
                ('type_collaborator_name', models.CharField(max_length=24)),
            ],
        ),
        migrations.CreateModel(
            name='TypeReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_report_code', models.CharField(max_length=12)),
                ('type_report_name', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_code', models.CharField(max_length=9, unique=True)),
                ('student_name', models.CharField(max_length=24)),
                ('student_birth_date', models.DateField(max_length=10)),
                ('student_id', models.CharField(max_length=10)),
                ('student_email', models.CharField(max_length=50)),
                ('student_phone_number', models.CharField(max_length=12)),
                ('student_ICFES_score', models.IntegerField()),
                ('donor_student_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MSDE_App.donor')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_code', models.CharField(auto_created=True, max_length=14, unique=True)),
                ('report_date', models.DateField(max_length=10)),
                ('philanthropy_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MSDE_App.philanthropymember')),
                ('student_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MSDE_App.student')),
                ('type_report_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MSDE_App.typereport')),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_code', models.CharField(auto_created=True, max_length=20, unique=True)),
                ('alert_description', models.TextField(default='Ingrese una descripcion')),
                ('alert_sender', models.CharField(default='Emisor alarma', max_length=100)),
                ('type_alert', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MSDE_App.typealert', to_field='alert_type_code')),
            ],
        ),
    ]
