# Generated by Django 4.2.5 on 2023-10-23 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MSDE_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
