# Generated by Django 4.2.5 on 2023-10-07 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MSDE_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_surname',
            field=models.CharField(max_length=24, null=True),
        ),
    ]
