# Generated by Django 4.2.5 on 2023-10-07 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MSDE_App', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alert',
            old_name='student',
            new_name='student_code',
        ),
        migrations.CreateModel(
            name='ExtraAcademic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra_academic_name', models.CharField(max_length=100)),
                ('extra_academic_hours', models.IntegerField()),
                ('student_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MSDE_App.student')),
            ],
        ),
        migrations.CreateModel(
            name='CreaQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crea_query_date', models.DateField()),
                ('crea_query_info', models.CharField(max_length=500)),
                ('student_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MSDE_App.student')),
            ],
        ),
        migrations.CreateModel(
            name='AcademicBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_balance_career', models.CharField(max_length=50)),
                ('academic_balance_subjects', models.CharField(max_length=50)),
                ('academic_balance_schedule', models.CharField(max_length=50)),
                ('academic_balance_additions', models.CharField(max_length=50)),
                ('academic_balance_cancellations', models.CharField(max_length=50)),
                ('academic_balance_semester_average', models.FloatField()),
                ('academic_balance_total_average', models.FloatField()),
                ('student_code', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='MSDE_App.student')),
            ],
        ),
    ]
