# Generated by Django 4.2.5 on 2023-09-18 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MSDE_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_ICFES_score',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='Authenthication',
        ),
    ]
