# Generated by Django 4.2.5 on 2023-10-07 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MSDE_App', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collaborator',
            name='id',
        ),
        migrations.AlterField(
            model_name='collaborator',
            name='collaborator_code',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
