# Generated by Django 4.2.5 on 2023-10-02 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MSDE_App', '0002_alert_alert_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='type_alert',
        ),
        migrations.AddField(
            model_name='alert',
            name='type_alert_code',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='MSDE_App.typealert'),
            preserve_default=False,
        ),
    ]
