# Generated by Django 4.2.5 on 2023-09-19 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MSDE_App', '0002_alter_student_student_icfes_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='id',
        ),
        migrations.RemoveField(
            model_name='collaborator',
            name='id',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='id',
        ),
        migrations.RemoveField(
            model_name='philanthropymember',
            name='id',
        ),
        migrations.RemoveField(
            model_name='report',
            name='id',
        ),
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.RemoveField(
            model_name='typecollaborator',
            name='id',
        ),
        migrations.RemoveField(
            model_name='typereport',
            name='id',
        ),
        migrations.AlterField(
            model_name='alert',
            name='alert_code',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='collaborator',
            name='collaborator_code',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='donor',
            name='donor_code',
            field=models.CharField(max_length=12, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='philanthropymember',
            name='philanthropy_member_code',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_code',
            field=models.CharField(max_length=14, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_birth_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_code',
            field=models.CharField(max_length=9, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='typecollaborator',
            name='type_collaborator_code',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='typereport',
            name='type_report_code',
            field=models.CharField(max_length=12, primary_key=True, serialize=False, unique=True),
        ),
    ]
