# Generated by Django 4.2.5 on 2023-10-07 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MSDE_App', '0002_rename_student_alert_student_code_extraacademic_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alert',
            old_name='student_code',
            new_name='student',
        ),
    ]
