# Generated by Django 4.2.5 on 2023-09-20 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MSDE_App', '0002_student_donor_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='donor_student',
            new_name='donor_student_code',
        ),
        migrations.AlterField(
            model_name='alert',
            name='alert_code',
            field=models.CharField(auto_created=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='donor',
            name='donor_code',
            field=models.CharField(max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_code',
            field=models.CharField(auto_created=True, max_length=14, unique=True),
        ),
    ]
