# Generated by Django 4.2.5 on 2023-10-29 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MSDE_App', '0003_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='message_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
