# Generated by Django 4.2.5 on 2023-10-08 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MSDE_App', '0002_remove_collaborator_id_and_more'),
        ('MSDE_App', '0003_rename_student_code_alert_student'),
    ]

    operations = [
    ]
