# Generated by Django 4.2.5 on 2023-10-01 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MSDE_App', '0003_rename_donor_student_student_donor_student_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='alert_description',
            field=models.TextField(default='Ingrese una descripcion'),
        ),
        migrations.AddField(
            model_name='alert',
            name='alert_sender',
            field=models.CharField(default='Emisor alarma', max_length=100),
        ),
    ]
