# Generated by Django 4.2.5 on 2023-11-19 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MSDE_App', '0003_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborator',
            name='collaborator_type',
            field=models.CharField(choices=[('Bienestar Universitario', 'Bienestar Universitario'), ('Registro Académico', 'Registro Académico'), ('Director de Programa', 'Director de Programa'), ('Apoyo Financiero', 'Apoyo Financiero')], max_length=30, null=True, unique=True),
        ),
    ]
