# Generated by Django 4.2.5 on 2023-09-19 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MSDE_App', '0003_remove_alert_id_remove_collaborator_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='type_report_code',
        ),
        migrations.AddField(
            model_name='student',
            name='id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='typereport',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='typereport',
            name='type_report_code',
            field=models.CharField(max_length=12),
        ),
    ]
