# Generated by Django 4.2.5 on 2023-10-02 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MSDE_App', '0003_rename_donor_student_student_donor_student_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collaborator',
            name='collaborator_allow_alert',
        ),
    ]
