# Generated by Django 4.2.5 on 2023-10-02 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MSDE_App', '0003_remove_alert_type_alert_alert_type_alert_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alert',
            old_name='type_alert_code',
            new_name='type_alert',
        ),
    ]
