# Generated by Django 4.2.5 on 2023-09-25 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MSDE_App', '0003_rename_donor_student_student_donor_student_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='philanthropymember',
            name='philanthropy_member_email',
            field=models.CharField(default='default@gmail.com', max_length=50),
        ),
    ]
