# Generated by Django 4.2.5 on 2023-09-26 01:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('MSDE_App', '0003_rename_donor_student_student_donor_student_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='alert_date',
            field=models.DateField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alert',
            name='alert_code',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
