# Generated by Django 4.2.5 on 2023-10-08 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MSDE_App', '0004_remove_typereport_type_report_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='report_code',
        ),
    ]
