# Generated by Django 4.2.5 on 2023-10-01 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MSDE_App', '0004_alert_alert_description_alert_alert_sender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typealert',
            name='type_alert_code',
        ),
        migrations.RemoveField(
            model_name='typealert',
            name='type_alert_name',
        ),
        migrations.AddField(
            model_name='alert',
            name='type_alert',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MSDE_App.typealert', to_field='alert_type_code'),
        ),
        migrations.AddField(
            model_name='typealert',
            name='alert_type_code',
            field=models.CharField(max_length=12, null=True, unique=True),
        ),
    ]
