# Generated by Django 4.2.5 on 2023-09-19 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MSDE_App', '0004_remove_report_type_report_code_student_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
    ]
