# Generated by Django 4.2.5 on 2023-09-19 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MSDE_App', '0005_remove_student_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='philanthropy_member',
        ),
        migrations.RemoveField(
            model_name='report',
            name='student_code',
        ),
    ]
