# Generated by Django 4.2.5 on 2023-10-08 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MSDE_App', '0005_remove_report_report_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='philanthropymember',
            name='philanthropy_member_email',
            field=models.CharField(default='example@gmail.com', max_length=50),
        ),
    ]
