# Generated by Django 4.2.5 on 2023-11-20 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MSDE_App', '0004_message_message_date'),
        ('MSDE_App', '0005_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
    ]
