# Generated by Django 4.2.5 on 2023-09-19 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MSDE_App', '0006_remove_report_philanthropy_member_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='philanthropy_member_code',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='MSDE_App.philanthropymember'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='student_code',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='MSDE_App.student'),
            preserve_default=False,
        ),
    ]
