# Generated by Django 4.2.5 on 2023-09-19 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MSDE_App', '0007_report_philanthropy_member_code_report_student_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='type_report_code',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='MSDE_App.typereport'),
            preserve_default=False,
        ),
    ]
