# Generated by Django 4.2.5 on 2023-09-19 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MSDE_App', '0008_report_type_report_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='philanthropy_member_code',
            new_name='philanthropy_member',
        ),
        migrations.AddField(
            model_name='alert',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collaborator',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donor',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='philanthropymember',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='typecollaborator',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alert',
            name='alert_code',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='collaborator',
            name='collaborator_code',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='donor',
            name='donor_code',
            field=models.CharField(max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='philanthropymember',
            name='philanthropy_member_code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_code',
            field=models.CharField(max_length=14, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_birth_date',
            field=models.DateField(max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_code',
            field=models.CharField(max_length=9, unique=True),
        ),
        migrations.AlterField(
            model_name='typealert',
            name='type_alert_code',
            field=models.CharField(max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='typecollaborator',
            name='type_collaborator_code',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='typereport',
            name='type_report_code',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
