# Generated by Django 4.2.5 on 2023-09-19 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MSDE_App', '0009_rename_philanthropy_member_code_report_philanthropy_member_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='alert_code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='collaborator',
            name='collaborator_code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='donor',
            name='donor_code',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_code',
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name='typealert',
            name='type_alert_code',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='typecollaborator',
            name='type_collaborator_code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='typereport',
            name='type_report_code',
            field=models.CharField(max_length=12),
        ),
    ]
