# Generated by Django 4.2.5 on 2023-09-19 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MSDE_App', '0010_alter_alert_alert_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_code',
            field=models.CharField(max_length=9),
        ),
    ]
