from .student_view import *
from .home_view import *
from .alert_view import *
from .send_info_view import *
from .logout_view import *
from .collaborator_view import *
from .registrate_view import *
from .info_dissemination import *
from .update_info import *
